### ISSUE TITLE
[FEATURE REQUEST] Enable swipe

### ISSUE THREAD

**Issue by KendallDoesCoding** [anantdubey16/Myportfolio#1]
In the section with all your projects, you should enable swipe as it will be very helpful to users on mobile, using laptop keypad and more convenient  :)

![image](https://user-images.githubusercontent.com/84712013/168414219-0afea660-9613-46db-86df-cadce5f06668.png)

**Comment by KendallDoesCoding** [comment]
Sorry, it already exist, I was trying to swipe another way using my laptop keypad, my bad.

**Comment by anantdubey16** [comment]
thanks for viewing it
